services:
  db:
    container_name: db
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ${DB_NAME:-postgresdb}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dbpassword}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  pg_data:
